---

- name: Ansible Playbook for building webcampaign

- hosts: webcampaign-image-provider
  roles:
    - webcam
    - image-uploader
  remote_user: pi
  become: yes

- hosts: webcampaign-image-store
  roles:
    - s3-website

- hosts: webcampaign-image-indexer
  roles:
    - lamda-indexer
